= Nimbuslabel module for Appcelerator
:hp-tags: label,appcelerator,module
:published_date: 2015-02-10

Using rich labels in Appcelerator apps has always been a challenge. Basically you had to fall back to using a webview to use html/css to style text. This has a very big downside: memory usage. There are several modules that address this problem and now (since SDK 3.2) also Appcelerator has a solution with http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.iOS.AttributedString[attributed strings]. However, all of these modules and the native attributed label solutions did not meet the demands I had.

'''

A search for native iOS solutions lead to the http://nimbuskit.info/[NimbusKit framework]. Part of NimbusKit is an attributed label implementation. It has features to mark ranges of text to have a color and/or link. Taps on links are handled.

Still the Nimbus attributed label has some missing features. The first one is detecting a tap&hold (longpress) on links. The second missing feature is passing the tap coordinates to the calling code.

I decided to create an Appcelerator module based on the Nimbus attributed label code anyway and add the two missing featuers.

== The problem with Appcelerator attributed strings

Although the implementation that comes with Appcelerator for attributed strings works for simple tasks where just a few text labels need styling. Building an app that uses styled labels in a tableview/listview (think Twitter like lists of posts) is where the problems start. Because (dynamic) tableviews are just too slow I will only go into using listviews with templates. And listview templates is where the problem starts if you want to use labels with attributed strings. A simplified piece of code from the appcelerator documentation:


[source,javascript]
----
var attr = Titanium.UI.iOS.createAttributedString({ // <1>
    text: text,
    attributes: [
        // Underlines text
        {
            type: Titanium.UI.iOS.ATTRIBUTE_UNDERLINES_STYLE,
            value: Titanium.UI.iOS.ATTRIBUTE_UNDERLINE_STYLE_SINGLE,
            range: [0, text.length]
        },
        // Sets a background color
        {
            type: Titanium.UI.iOS.ATTRIBUTE_BACKGROUND_COLOR,
            value: "red",
            range: [text.indexOf('Appcelerator'), ('Appcelerator').length]
        },
        {
            type: Titanium.UI.iOS.ATTRIBUTE_BACKGROUND_COLOR,
            value: "blue",
            range: [text.indexOf('Titanium'), ('Titanium').length]
        },
        {
            type: Titanium.UI.iOS.ATTRIBUTE_BACKGROUND_COLOR,
            value: "yellow",
            range: [text.indexOf('rocks!'), ('rocks!').length]
        },
        // Sets a foreground color
        {
            type: Titanium.UI.iOS.ATTRIBUTE_FOREGROUND_COLOR,
            value: "orange",
            range: [0,  text.length]
        },
        {
            type: Titanium.UI.iOS.ATTRIBUTE_FOREGROUND_COLOR,
            value: "black",
            range: [text.indexOf('rocks!'), ('rocks!').length]
        }
    ]
});

var label = Titanium.UI.createLabel({ // <2>
    left: 20,
    right: 20,
    height: Titanium.UI.SIZE,
    attributedString: attr // <3>
});
----
<1> first create an attributed string
<2> create a label
<3> assign the attributed string created earlier to the label

You might notice the problem already: you have to create the attributed string before it can be used in a label. When using listviews with templates this is not possible (well it is but it defeats the reason why listviews were added in the first place: speed).

Another problem (for me) with attributed strings is that links are always underlined and blue. Also, only a http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.iOS-property-ATTRIBUTE_LINK[longpress] is possible with attributed strings, no single taps.

== The solution with nimbuslabel module

By updating and adding a little to the nimbuslabel code I was able to overcome the issues mentioned above. You only have to create one object, therefor it can be used in listview templates. It has has both click and longpress events (although I did name those singletap and tapandhold). And links can have any color you like.

Sample code for a template using nimbuslabel:

----
// a simple template

var templatePost = {
  properties: {
    height: Ti.UI.SIZE,
    selectionStyle: Ti.UI.iPhone.ListViewCellSelectionStyle.NONE,
  },
  childTemplates: [
  {
      type: 'NimbusLabelLabel',
      bindId: 'textlabel',
      properties: {
        type: 'textlabel',
        width:Ti.UI.FILL,
        height:Ti.UI.SIZE,
        touchEnabled: true,
        bubbleParent: false,
      },
      events: {
        singletap: yourSingletapCallback,
        tapandhold: yourLongpressCallback,
      },
    }
  ]
};

// code to push a row in the listview
var row = {
  itemId: id,
  postcontent: {
    attributedText: {text: posttext, attributes: attributes},
    highlightedLinkBackgroundColor: Instance.UI.colors.barColor,
  }
};


----


== Download

The nimbuslabel module is available on my https://github.com/ludolphus/Nimbuslabel[github]. Check the dist folder for a pre-compiled verison of the module.

== Apps using the Appcelerator nimbuslabel module

https://itunes.apple.com/us/app/chimp-app.net-client-includes/id619961141?mt=8[Chimp]

https://itunes.apple.com/us/app/filez-file-manager-for-your/id663233773?mt=8[FileZ]


*your app here*



